const photos = [
  {
    img: '/img/1.jpg',
    title1: 'Queen of ',
    title2: 'the Sea',
    subtitle: 'Osaka, 1986',
    desc: 'Hidesato felt very sorry for the Dragon King on hearing his story, and readily promised to do what he could to help him.',
    id: 1,
  },
  {
    img: '/img/2.jpg',
    title1: "Hinata's",
    title2: 'Trouble',
    subtitle: 'Kyoto, 1986',
    desc: 'His power was immense, for he was the ruler of all sea creatures both great and small, and in his keeping were the Jewels of the Ebb and Flow of the Tide.',
    id: 2,
  },
  {
    img: '/img/3.jpg',
    title1: "Dragon's",
    title2: 'Journey',
    subtitle: 'Nagoya, 1986',
    desc: 'Calling all his fish retainers together, he chose several of them as ambassadors to go through the sea and seek for a young Dragon Princess who would be his bride.',
    id: 3,
  },
  {
    img: '/img/4.jpg',
    title1: 'Prince',
    title2: 'Yamato',
    subtitle: 'Tokyo, 1986',
    desc: 'The King fell in love with her at once, and the wedding ceremony was celebrated with great splendor.',
    id: 4,
  },
  {
    img: '/img/5.jpg',
    title1: 'Kumaso',
    title2: '&amp; Haru',
    subtitle: 'Sapporo, 1986',
    desc: 'When the hare heard these kind words he felt very grateful to the man, and encouraged by his gentle manner the hare told him all that had befallen him.',
    id: 5,
  },
  {
    img: '/img/6.jpg',
    title1: "Botan's",
    title2: 'Dream',
    subtitle: 'Sendai, 1986',
    desc: 'Okuni-nushi-no-Mikoto is worshiped by the people in some parts of Japan, as a god, and the hare has become famous as “The White Hare of Inaba”.',
    id: 6,
  },
  {
    img: '/img/7.jpg',
    title1: 'The Gate',
    title2: 'of Rashoi',
    subtitle: 'Kyoto, 1986',
    desc: 'Nearly two thousand years ago this sword was kept at the shrines of Ite, the temples dedicated to the worship of Amaterasu, the great and beautiful Sun Goddess from whom the Japanese Emperors are said to be descended.',
    id: 7,
  },
  {
    img: '/img/8.jpg',
    title1: 'Faithful',
    title2: 'Knights',
    subtitle: 'Kobe, 1986',
    desc: 'At last King Keiko ordered his younger son Prince Yamato to subdue the brigands and, if possible, to rid the land of their evil lives.',
    id: 8,
  },
  {
    img: '/img/9.jpg',
    title1: 'Five Colors',
    title2: 'for Jokwa',
    subtitle: 'Hiroshima, 1986',
    desc: 'There is a story of knightly adventure and daring which explains why the name of the sword was changed from that of Murakumo to Kasanagi, which means grass clearing.',
    id: 9,
  },
  {
    img: '/img/10.jpg',
    title1: "Shikuyu's",
    title2: 'Charm',
    subtitle: 'Kumamoto, 1986',
    desc: 'He at once made ready to start, and great was the stir in the precincts of the Palace as he and his trusty followers gathered together and prepared for the expedition, and polished up their armor and donned it.',
    id: 10,
  },
];

export { photos };
